---
- name: Update Pool Members
  hosts: bigip
  gather_facts: false
  connection: local

  tasks:

  - name: URI Patch
    uri:
      url: "https://{{ ansible_host }}/mgmt/shared/appsvcs/declare"
      method: "PATCH"
      user: "{{ creds_big_ip.user }}"
      password: "{{ creds_big_ip.password }}"
      validate_certs: no
      body: "{{ lookup('template', '../j2/updates_members.j2') }}"
      body_format: json
